port: 8000
rotationtime: 200000
theme: dark

externalconfig:
  jenkins:
    baseUrl: https://jenkins.demo.fr
    user: demo
    password: demo

dashboards:
  - title: 'My second dashboard'
    components:
      - type: iframe
        title: 'Grafana working'
        width: 1
        height: 1
        column: 0
        row: 0
        data:
          url: 'https://play.grafana.org/dashboard/snapshot/1eFZHlo5cI5Bv2uEadHY1gLNZK6x75ZW'
          base: 'https://play.grafana.org'
          proxy-port: 8888
          proxy-hostname: localhost
          proxy-protocol: http
