port: 8000
rotationtime: 200000
theme: dark

externalconfig:
  jenkins:
    baseUrl: https://jenkins.demo.fr
    user: demo
    password: demo

dashboards:
  - title: 'My second dashboard'
    components:
      - type: health
        title: 'Inte01 health check'
        width: 1
        height: 1
        column: 0
        row: 0
        data:
          url: 'https://toto/internal/actuator/health'
          format: json
          path: $.status
          size: 30px
          UP: green
          WARN: orange
          DOWN: red
          nil: gray