FROM arm32v7/golang:alpine AS builder
ENV GOARCH=arm
ENV GOOS=linux
RUN apk add git gcc g++ binutils-gold

WORKDIR /app
COPY . .
RUN /app/build.sh
RUN chmod -R 777 /app

FROM arm32v7/alpine:latest AS production
WORKDIR /app
COPY --from=builder /app/plugins /app/plugins
COPY --from=builder /app/index.html /app/index.html
COPY --from=builder /app/favicon.ico /app/favicon.ico
COPY --from=builder /app/dasher /app/dasher

CMD ["/app/dasher"]
